from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional


class AIQueryRequest(BaseModel):
    snapshot_id: str = Field(..., description="UUID snapshot identifier of target repository.")
    query: str = Field(..., description="Query instruction for the AI agent loop.")
    token_limit: Optional[int] = Field(4000, description="Token budget window limit.")


class AIResponseTask(BaseModel):
    agent: str
    tool: str
    priority: int
    arguments: Optional[Dict[str, Any]] = None


class AIPlan(BaseModel):
    intent: str
    complexity: str
    tasks: List[AIResponseTask]


class AIChatResponse(BaseModel):
    response: str = Field(..., description="Synthesized final AI markdown report.")
    plan: AIPlan = Field(..., description="Structured tasks plan generated by Planner.")
    total_cost: float = Field(..., description="Estimated gateway usage cost in USD.")
    total_tokens: int = Field(..., description="Total input and output tokens consumed.")
